CREATE AVAILABILITY GROUP [dlbsql-s01]
WITH (AUTOMATED_BACKUP_PREFERENCE = PRIMARY)
FOR DATABASE [Darden]
REPLICA ON N'dlbsqls01'
WITH (ENDPOINT_URL = N'TCP://dlbsqls01.yosemite.local:5022'
, FAILOVER_MODE = AUTOMATIC, AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, SESSION_TIMEOUT = 10, BACKUP_PRIORITY = 50
, PRIMARY_ROLE(ALLOW_CONNECTIONS = ALL), SECONDARY_ROLE(ALLOW_CONNECTIONS = ALL));

CREATE ENDPOINT [Hadr_endpoint]
STATE = STARTED
AS TCP ( LISTENER_PORT = 5022 )
FOR DATABASE_MIRRORING (ROLE = ALL);

ALTER AVAILABILITY GROUP [dlbsql-s01]
ADD LISTENER N'dlbsql-s01' (
WITH IP
((N'10.12.133.251', N'255.255.255.0')
)
, PORT=1433);

ALTER AVAILABILITY GROUP [dlbsql-s01] 
ADD REPLICA ON 'dlbsqls02'   
WITH (ENDPOINT_URL = N'TCP://dlbsqls02.yosemite.local:5022'
, FAILOVER_MODE = AUTOMATIC, AVAILABILITY_MODE = SYNCHRONOUS_COMMIT, SESSION_TIMEOUT = 10, BACKUP_PRIORITY = 50
, PRIMARY_ROLE(ALLOW_CONNECTIONS = ALL), SECONDARY_ROLE(ALLOW_CONNECTIONS = ALL));

:Connect dlbsqls02

ALTER AVAILABILITY GROUP [dlbsql-s01] JOIN;

CREATE ENDPOINT [Hadr_endpoint]
STATE = STARTED
AS TCP ( LISTENER_PORT = 5022 )
FOR DATABASE_MIRRORING (ROLE = ALL);