-------------------------------------------------------------------------------
-- Configure read-only routing

USE [master]

ALTER AVAILABILITY GROUP [agName]
 MODIFY REPLICA ON
N'server01' WITH 
(PRIMARY_ROLE (ALLOW_CONNECTIONS = READ_WRITE));
ALTER AVAILABILITY GROUP [agName]
 MODIFY REPLICA ON
N'server01' WITH 
(SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL));
ALTER AVAILABILITY GROUP [agName]
 MODIFY REPLICA ON
N'server01' WITH 
(SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://server01.yosemite.local:1433'));

ALTER AVAILABILITY GROUP [agName]
 MODIFY REPLICA ON
N'server02' WITH 
(PRIMARY_ROLE (ALLOW_CONNECTIONS = READ_WRITE));
ALTER AVAILABILITY GROUP [agName]
 MODIFY REPLICA ON
N'server02' WITH 
(SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL));
ALTER AVAILABILITY GROUP [agName]
 MODIFY REPLICA ON
N'server02' WITH 
(SECONDARY_ROLE (READ_ONLY_ROUTING_URL = N'TCP://server02.yosemite.local:1433'));

ALTER AVAILABILITY GROUP [agName] 
MODIFY REPLICA ON
N'server01' WITH 
(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('server02','server01')));

ALTER AVAILABILITY GROUP [agName] 
MODIFY REPLICA ON
N'server02' WITH 
(PRIMARY_ROLE (READ_ONLY_ROUTING_LIST=('server01','server02')));
GO